// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getDatabaseUrl() {
  if (process.env.VERCEL_ENV === "production") {
    return process.env.PROD_DATABASE_URL || process.env.DATABASE_URL || "";
  }
  if (process.env.VERCEL_ENV === "preview") {
    return process.env.PREVIEW_DATABASE_URL || process.env.DATABASE_URL || "";
  }
  // local/dev fallback
  return process.env.DATABASE_URL || "";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
